$mainMod = SUPER

$terminal = kitty 
$fileManager = thunar
$menu = hyprlauncher 

bind = $mainMod, T, exec, $terminal 
bind = ALT, Tab, cyclenext, next

bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod Shift, right, movewindow, r
bind = $mainMod Shift, l, movewindow, r
bind = $mainMod Shift, up, movewindow, u
bind = $mainMod Shift, k, movewindow, u
bind = $mainMod Shift, down, movewindow, d
bind = $mainMod Shift, j, movewindow, d

bind = $mainMod, W, killactive,
bind = $mainMod, F, fullscreen,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, SUPER_L, exec, $menu 

#Media
bindl = $mainMod, N,  exec, playerctl next
bindl = $mainMod, M,  exec, playerctl previous 
bindl = $mainMod, P,  exec, playerctl play-pause

bind = $mainMod SHIFT, S, exec, grim -g "$(slurp -d)" - | wl-copy

bind = $mainMod, left, movefocus, l
bind = $mainMod, h, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, l, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, k, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, j, movefocus, d

bind = $mainMod, 1, workspace ,1
bind = $mainMod, 2, workspace ,2
bind = $mainMod, 3, workspace ,3
bind = $mainMod, 4, workspace ,4
bind = $mainMod, 5, workspace ,5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273,resizewindo 

bind = ALT, LEFT, resizeactive, -50 0
bind = ALT, h, resizeactive, -50 0
bind = ALT, RIGHT, resizeactive, 50 0
bind = ALT, l, resizeactive, 50 0
bind = ALT, UP, resizeactive, 0 -50
bind = ALT, k, resizeactive, 0 -50
bind = ALT, DOWN, resizeactive, 0 50
bind = ALT, j, resizeactive, 0 50

bind = ,XF86AudioPlay, exec, playerctl play-pause
