windowrule {
	name = opengl blackbox
	match:title = Test Title

	float = true
}
windowrule {
	name = zen no opacity
	match:class = zen

	opacity = 1.0 override
}

windowrule {
	name = Picture-in-Picture
	match:title = Picture-in-Picture
	# match:class = zn
	float = true
}

windowrule {
	name = emulator
	match:title = Emulator
	# match:class = zn
	float = true
}

